import { Poppins } from "next/font/google";
import "../globals.css";
import QueryProvider from "@/components/QueryProvider";
import AuthWrapper from "@/components/AuthWrapper";
import Header from "@/components/Header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <QueryProvider>
          <AuthWrapper userRole="admin">
            <Header />
            {children}
          </AuthWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
